version: "3.1"
services:
  nies:
    build:
      context: .
      dockerfile: Dockerfile
    image: nepolin/hierarchical_review_mx:latest
    command: bash
    volumes:
      - $PWD:/workdir
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nepolin/hierarchical_review_mx:latest
    entrypoint: ["streamlit", "run", "hr_MX_app.py", "--server.port=8502", "--server.address=0.0.0.0"]
    volumes:
      - $PWD:/workdir
    ports:
      - "8502:8502"