name: cron-schedule-updater
on:
  schedule:
    - cron: '40 7 * * */5'

jobs:
  empty_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - run: git config user.email "nepo@nies.futbol"
    - run: git config user.name "Nepo Rojas"

    - name: Create Empty Commit
      run: echo $(date) > log_automatic_commit.tex
    - run: git add log_automatic_commit.tex
    - run: git commit -m "⌛🤖 Log automatic commit"


    - name: Push Empty Commit
      run: git push origin develop  # Change 'main' to your branch name
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
